<a href="<?php echo get_the_permalink(); ?>" class="group"
    data-component="archive-card">
    <section>
    <div class="content">
        <div class="featured-image rectangle wide outline">
        </div>
        <div>
            <h1><?php echo get_the_title(); ?></h1>
        </div>
        <p><?php echo get_the_excerpt(); ?></p>
    </div>
    </section>
</a>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         